import {catalog,shapes,cords,knots,clone,makeBead,starter,measure,moveItem,validate,materials,registerMaterial,validateMaterial,modes,allBeads,strandOf,isMainBead,removeBead,insertBeadAt,makeBranch,setMode,modeStarter} from './model.js';
import {esc,icon,beadSvg,braceletSvg} from './visuals.js';
import {BraceletViewer} from './three-view.js';
import {initPhotoEditor} from './photo-editor.js';
import {createDirectEditor} from './direct-editor.js';
import {read as readStorage,write as writeStorage} from './storage.js';
const $=s=>document.querySelector(s),DRAFT='yichuan.draft.v1',SAVED='yichuan.saved.v1';
let state=starter(),storageOK=true;try{const raw=await readStorage(DRAFT,null);const legacy=raw?null:localStorage.getItem(DRAFT);if(raw||legacy)state=validate(raw||JSON.parse(legacy));}catch{storageOK=false;}
let myMaterials=[];try{myMaterials=(await readStorage('photos',[])).map(validateMaterial);myMaterials.forEach(registerMaterial);}catch{storageOK=false;}
for(const c of state.customMaterials||[])if(!myMaterials.some(x=>x.id===c.id))myMaterials.push(c);
let selected=state.beads[0]?.id||null,category='文玩珠',query='',inspector='bead',numbers=false,viewMode='2d',viewer=null,viewError=false,bg='sand',zoom=1,history=[],future=[],insertMode='after',saved=[],lastFocus=null,activeStrand='main',mobilePanel='materials',flatView={zoom:1,x:0,y:0};
try{saved=await readStorage(SAVED,null)||JSON.parse(localStorage.getItem(SAVED)||'[]');if(!Array.isArray(saved))saved=[];saved=saved.flatMap(item=>{try{return [{id:item.id,at:item.at,data:validate(item.data)}];}catch{return [];}});}catch{saved=[];}
const app=$('#app'),dialog=$('#dialog');
const photoEditor=initPhotoEditor({toast,onAdd:async c=>{if(allBeads(state).length>=600)throw Error('方案最多 600 个元素，请先删去一些。');if(new Set(allBeads(state).filter(b=>b.material.startsWith('photo-')).map(b=>b.material)).size>=12)throw Error('每份方案最多 12 种照片素材，请先移除一种。');if(myMaterials.length>=30)throw Error('本机材料盒最多保存 30 种照片素材，请先删除不需要的素材。');const next=[...myMaterials,c];await writeStorage('photos',next);myMaterials=next;registerMaterial(c);category='我的素材';query='';add(c.id);}});
const selectedBead=()=>allBeads(state).find(b=>b.id===selected);
const currentStrand=()=>strandOf(state,selected)||(state.branches||[]).find(b=>b.id===activeStrand)||{id:'main',name:'主串',beads:state.beads};
const editor=createDirectEditor({getState:()=>state,getViewer:()=>viewMode==='3d'&&!viewError?viewer:null,getMode:()=>viewMode,select:selectBead,getFlatView:()=>flatView,onFlatView:setFlatView,commit:(id,target)=>{const strand=strandOf(state,id);if(!strand)return;const index=strand.beads.findIndex(b=>b.id===id);if(!target.remove&&index===target.index)return;selected=id;activeStrand=strand.id;change(()=>{if(target.remove)removeBead(state,id);else insertBeadAt(state,id,target.index);},target.remove?'已删除珠子，可点撤销恢复。':'排列已更新。');}});
function setFlatView(v){flatView={zoom:Math.max(.55,Math.min(8,v.zoom)),x:v.x,y:v.y};zoom=flatView.zoom;const svg=$('#preview #bracelet-svg');if(svg)svg.style.transform=`translate(${flatView.x}px,${flatView.y}px) scale(${flatView.zoom})`;const label=$('#zoom-value');if(label)label.textContent=Math.round(zoom*100)+'%';const plus=$('[data-action="zoom-in"]'),minus=$('[data-action="zoom-out"]');if(plus)plus.disabled=zoom>=8;if(minus)minus.disabled=zoom<=.55;}

const btn=(action,label,ico,cls='',extra='')=>`<button type="button" data-action="${action}" class="${cls}" ${extra}>${ico?icon(ico):''}<span>${label}</span></button>`;
const iconBtn=(action,label,ico,extra='')=>`<button type="button" data-action="${action}" class="icon-btn" title="${label}" aria-label="${label}" ${extra}>${icon(ico)}</button>`;
const options=(items,current)=>items.map(x=>`<option ${x===current?'selected':''} value="${esc(x)}">${esc(x)}</option>`).join('');
const input=(label,field,value,min,max,step=1,unit='mm',scope='bead')=>`<label class="field"><span>${label}</span><div class="unit-input"><input type="number" data-field="${field}" data-scope="${scope}" value="${value}" min="${min}" max="${max}" step="${step}" aria-label="${label}"><span>${unit}</span></div></label>`;
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3300);}
function persist(){state.version=3;state.customMaterials=[...new Set(allBeads(state).map(b=>b.material))].map(id=>catalog.find(c=>c.id===id)).filter(c=>c?.image);const snapshot=clone(state);writeStorage(DRAFT,snapshot).then(()=>{storageOK=true;}).catch(()=>{storageOK=false;const label=$('.autosave');if(label){label.textContent='保存失败，请导出备份';label.classList.add('warning');}toast('本机保存失败，请导出含照片的 JSON 备份。');});}
function change(fn,message){history.push(clone(state));if(history.length>40)history.shift();future=[];fn();if(!allBeads(state).some(b=>b.id===selected))selected=currentStrand().beads[0]?.id||null;activeStrand=currentStrand().id;persist();render();if(message)toast(message);}
function logo(){return `<span class="logo-mark"><svg viewBox="0 0 40 40" width="33" height="33" fill="none" aria-hidden="true"><circle cx="20" cy="8" r="4"/><circle cx="30.5" cy="14" r="4"/><circle cx="30.5" cy="26" r="4"/><circle cx="20" cy="32" r="4" fill="#c8a56d" stroke="#c8a56d"/><circle cx="9.5" cy="26" r="4"/><circle cx="9.5" cy="14" r="4"/></svg></span><span class="brand-name">一串<span>YICHUAN STUDIO</span></span>`;}
function render(){
 const m=measure(state),long=state.mode!=='bracelet',strand=currentStrand();app.innerHTML=`<header class="app-header"><a class="brand" href="./" aria-label="一串首页">${logo()}</a><nav aria-label="主导航"><button class="nav-active" data-action="studio">穿串工作台</button><button data-action="saved">我的方案</button></nav><div class="header-right">${iconBtn('help','使用指南','help')}</div></header>
 <main><section class="design-heading"><div class="name-row"><input id="design-name" aria-label="方案名称" maxlength="60" value="${esc(state.name)}"><span class="autosave ${storageOK?'':'warning'}">${icon(storageOK?'check':'help',13)} ${storageOK?'本机已保存':'请导出备份'}</span></div><div class="heading-actions">${btn('save','保存方案','save','secondary')}${btn('plan','穿串清单','arrow','primary')}</div></section>
 <section class="studio" data-mobile-panel="${mobilePanel}" aria-label="穿串工作台"><aside class="materials panel"><div class="panel-title"><h2>材料盒</h2><span class="small-label">点选穿入</span></div><div class="search-box">${icon('search',15)}<input id="material-search" placeholder="搜索珠子、配饰…" value="${esc(query)}" aria-label="搜索材料"></div><div class="category-tabs" role="tablist" aria-label="材料类别">${['文玩珠','黄金元素','隔片配饰','我的素材'].map(c=>`<button role="tab" aria-selected="${category===c}" data-category="${c}" class="${category===c?'active':''}">${c}</button>`).join('')}</div><button class="upload-material" data-action="upload-photo">${icon('image',17)} 添加自己的照片 <span>抠图 · 立体预览</span></button><div class="material-grid" id="material-grid">${renderCatalog()}</div><div class="materials-bottom"><div class="insert-options"><span>添加位置</span><select id="insert-mode" aria-label="添加位置">${options(['选中元素之后','排列末尾'],insertMode==='after'?'选中元素之后':'排列末尾')}</select></div><p>穿入${esc(strand.name)} · 点串上的珠子更换位置</p><button class="inspiration" data-action="templates">${icon('spark',17)}<span>从例串开始</span>${icon('right',15)}</button></div></aside>
 <div class="center-workspace"><div class="preview-panel panel theme-${bg}"><div class="mode-toolbar"><label><span class="sr-only">串型</span><select aria-label="串型" data-field="mode" data-scope="state">${Object.entries(modes).map(([v,label])=>`<option value="${v}" ${state.mode===v?'selected':''}>${label}</option>`).join('')}</select></label><span class="bead-summary">${m.mainCount}${state.targetCount?' / '+state.targetCount:''} 主珠${m.accessoryCount?` · ${m.accessoryCount} 配珠`:''}</span><div class="edit-history">${iconBtn('undo','撤销（Ctrl / ⌘ Z）','undo',history.length?'':'disabled')}${iconBtn('redo','重做（Ctrl / ⌘ Shift Z）','redo',future.length?'':'disabled')}</div></div>
 <div class="preview-toolbar"><div class="view-switch"><button data-action="view-2d" class="${viewMode==='2d'?'active':''}" aria-pressed="${viewMode==='2d'}">串上编辑</button><button data-action="view-3d" class="${viewMode==='3d'?'active':''}" aria-pressed="${viewMode==='3d'}">360°</button></div>${long?`<div class="layout-switch"><button data-action="layout-expanded" aria-pressed="${state.layout==='expanded'}">展开</button><button data-action="layout-coiled" aria-pressed="${state.layout==='coiled'}">盘绕</button>${state.layout==='coiled'?`<select aria-label="盘绕圈数" data-field="coilTurns" data-scope="state">${[2,3,4,5].map(v=>`<option value="${v}" ${state.coilTurns===v?'selected':''}>${v} 圈</option>`).join('')}</select>`:''}</div>`:''}${iconBtn('reset-view','复位视角','rotate')}</div>
 ${(state.branches||[]).length?`<div class="strand-toolbar"><label>正在编辑 <select id="strand-select" aria-label="正在编辑的串"><option value="main" ${strand.id==='main'?'selected':''}>主串</option>${state.branches.map(br=>`<option value="${br.id}" ${strand.id===br.id?'selected':''}>${esc(br.name)}</option>`).join('')}</select></label><span>支串可单独排列</span></div>`:''}
 <div id="preview" class="preview-canvas ${viewMode==='3d'?'is-three':''}" style="--zoom:1">${viewMode==='2d'?braceletSvg(state,{selected,numbers}):''}</div>
 <p class="gesture-hint">拖珠子排列 · 拖远松手删除 · 双指缩放${viewMode==='3d'?' · 拖空白旋转':''}</p><div class="canvas-bottom"><div class="surface-controls" aria-label="预览底色">${['sand','white','dark'].map(c=>`<button aria-label="${{sand:'暖砂',white:'月白',dark:'深灰'}[c]}底色" data-bg="${c}" class="surface-${c} ${bg===c?'chosen':''}"></button>`).join('')}</div><div class="canvas-tools">${iconBtn('zoom-out','缩小预览','minus',zoom<=.55?'disabled':'')}<span id="zoom-value">${Math.round(zoom*100)}%</span>${iconBtn('zoom-in','放大预览','plus',zoom>=8?'disabled':'')}<button data-action="numbers" class="number-toggle ${numbers?'active':''}" aria-pressed="${numbers}" title="显示元素编号" aria-label="显示元素编号">#</button></div>${viewMode==='3d'?iconBtn('auto-rotate',viewer?.auto?'暂停转动':'自动转动','rotate',`aria-pressed="${!!viewer?.auto}"`):''}${iconBtn('export-view','保存搭配图','image')}</div>
 ${allBeads(state).some(b=>b.material.startsWith('photo-'))?'<p class="preview-note">照片立体为近似形状，背面复用正面。</p>':''}
 </div><div class="mobile-workbench-tabs" role="tablist" aria-label="工作台工具">${[['materials','材料盒'],['bead','元素调整'],['bracelet','串与线材']].map(([v,label])=>`<button data-mobile="${v}" role="tab" aria-selected="${mobilePanel===v}">${label}</button>`).join('')}</div></div>
 <aside class="inspector panel"><div class="inspector-tabs" role="tablist" aria-label="参数类型"><button data-inspector="bead" role="tab" aria-selected="${inspector==='bead'}" class="${inspector==='bead'?'active':''}">元素调整</button><button data-inspector="bracelet" role="tab" aria-selected="${inspector==='bracelet'}" class="${inspector==='bracelet'?'active':''}">串与线材</button></div><div class="inspector-body">${inspector==='bead'?renderBeadInspector():renderBraceletInspector()}</div>${renderStats(m)}</aside></section>
 <footer class="app-footer"><button data-action="import" class="footer-import">${icon('import',14)} 导入方案</button><div>${['玩家社区','闲置交易','官方售卖'].map(v=>`<button data-action="future" data-feature="${v}">${v} <small>筹备中</small></button>`).join('')}</div></footer></main>`;
 if(viewMode==='3d')mountViewer();else setFlatView(flatView);
}
function renderStats(m){if(state.mode!=='bracelet')return `<div class="fit-card"><div class="fit-title"><span>长串参考</span><span>${m.mainCount} 主珠</span></div><div class="fit-values"><div><strong>${(m.span/10).toFixed(1)}<small> cm</small></strong><span>主串穿线长度</span></div><div><strong>${m.cordCm}<small> cm</small></strong><span>含支串的备线参考</span></div></div><p>隔片、三通、挂件和支串另计。盘绕只改变摆放，主串顺序不变。</p></div>`;return `<div class="fit-card"><div class="fit-title"><span>圈口参考</span><span class="fit-badge ${m.fit==='合适'?'good':'caution'}">${m.count<3?'待穿入':m.fit}</span></div><div class="fit-values"><div><strong>${(m.inner/10).toFixed(1)}<small> cm</small></strong><span>预估内周长</span></div><div><strong>${(m.target/10).toFixed(1)}<small> cm</small></strong><span>目标内周长</span></div></div><p>按尺寸估算，实物试戴后微调。</p></div>`;}
function branchSettings(){const strand=currentStrand();if(strand.id==='main')return selected?`<div class="branch-actions"><span>从选中珠子悬挂</span>${btn('add-counter','计数器',null,'secondary')}${btn('add-backcloud','背云',null,'secondary')}${btn('add-tassel','流苏',null,'secondary')}</div>`:'';return `<div class="branch-settings"><label class="field"><span>支串挂点</span><select id="branch-anchor" aria-label="支串挂点">${state.beads.map((b,i)=>`<option value="${b.id}" ${strand.anchor===b.id?'selected':''}>主串第 ${i+1} 颗 · ${esc(catalog.find(c=>c.id===b.material).name)}</option>`).join('')}</select></label><div class="branch-actions">${btn('flip-branch','切换悬挂方向',null,'secondary')}${btn('delete-branch','移除支串','trash','text-btn')}</div><p class="field-hint">材料穿入这条支串；切换“主串”可继续编辑主串。</p></div>`;}
function renderCatalog(){const library=catalog.filter(c=>!c.image||myMaterials.some(m=>m.id===c.id)||state.customMaterials?.some(m=>m.id===c.id));const list=library.filter(c=>(query?true:c.category===category)&&[c.name,c.caption,c.shape].join(' ').includes(query));return list.length?list.map(c=>`<div class="material-item"><button class="material-card" data-add="${c.id}" aria-label="添加${esc(c.name)}"><div class="material-art">${beadSvg({...c,material:c.id,length:c.length||c.size},68)}<span class="add-chip">+</span>${c.category==='黄金元素'?'<span class="gold-label">AU</span>':''}</div><strong>${esc(c.name)}</strong><span>${c.size} mm · ${c.image?'照片素材':c.shape}</span></button>${c.image?`<button class="remove-photo" data-action="remove-photo" data-material="${c.id}" aria-label="从材料盒移除${esc(c.name)}">移出材料盒</button>`:''}</div>`).join(''):`<p class="empty-small">${category==='我的素材'?'还没有自己的素材。<br>点击上方按钮，添加珠子或黄金照片。':'还没有找到这类材料。<br>试试“菩提”或“金”。'}</p>`;}
function renderBeadInspector(){const b=selectedBead();if(!b)return `${branchSettings()}<div class="empty-inspector">${icon('sliders',30)}<h3>点选一颗，慢慢调整</h3><p>点击串上的元素，设置颜色、款式与尺寸。</p></div>`;const c=catalog.find(c=>c.id===b.material),idx=currentStrand().beads.indexOf(b);const shapeOptions=['隔片','三通','吊饰','流苏'].includes(c.shape)?[c.shape]:shapes;
 return `<div class="selected-card"><div>${beadSvg(b,57)}</div><span><small>${esc(currentStrand().name)} · 第 ${String(idx+1).padStart(2,'0')} 个元素</small><h3>${esc(c.name)}</h3><span>${c.category}</span></span></div><label class="field"><span>珠子种类 / 材料</span><select data-field="material" data-scope="bead" aria-label="珠子种类">${catalog.map(c=>`<option value="${c.id}" ${b.material===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label>${c.image?`<label class="field"><span>照片立体形状</span><select data-field="form" data-scope="bead" aria-label="照片立体形状">${[['round','圆珠'],['barrel','桶珠'],['relief','轮廓加厚']].map(([v,label])=>`<option value="${v}" ${b.form===v?'selected':''}>${label}</option>`).join('')}</select></label>${input('模型厚度','depth',b.depth||c.depth,.5,24,.5)}<p class="field-hint">背面复用正面照片。轮廓加厚适合异形黄金、吊饰；孔道不会自动还原。</p>`:`<label class="field"><span>款式</span><select data-field="shape" data-scope="bead" aria-label="款式">${options(shapeOptions,b.shape)}</select></label>`}<div class="field-row">${input('外径','size',b.size,2,24,.5)}${input('穿线长度','length',b.length,1,30,.5)}</div><p class="field-hint">外径影响粗细，穿线长度影响圈口。</p>${c.image?'<p class="field-hint">颜色保留照片原貌；拍照光线会影响呈现。</p>':`<div class="field"><span>颜色 <small>${b.color.toUpperCase()}</small></span><div class="color-palette">${['#e4d7b6','#eee6cc','#642e24','#6d9b8e','#ba553f','#d6a74e'].map(color=>`<button class="color-dot ${color.toLowerCase()===b.color.toLowerCase()?'active':''}" style="background:${color}" data-color="${color}" title="${color}" aria-label="颜色 ${color}"></button>`).join('')}<label class="custom-color" title="自定义颜色"><input type="color" aria-label="自定义元素颜色" value="${b.color}" data-field="color" data-scope="bead">${icon('plus',13)}</label></div></div>`}<button class="apply-all" data-action="apply-all">${icon('copy',14)} 应用到所有同种材料 <span>${allBeads(state).filter(x=>x.material===b.material).length}</span></button><div class="position-controls"><span>调整位置</span><div>${iconBtn('move-left','向前移动','left',idx===0?'disabled':'')}${iconBtn('move-right','向后移动','right',idx===currentStrand().beads.length-1?'disabled':'')}${iconBtn('duplicate','复制选中元素','copy')}${iconBtn('delete','删除选中元素','trash')}</div></div>${currentStrand().id==='main'?`<label class="count-main"><input type="checkbox" data-field="countAsMain" data-scope="bead" ${isMainBead(b)?'checked':''}>计入主珠数量</label>`:''}${branchSettings()}`;
}
function renderBraceletInspector(){return `${state.mode!=='bracelet'?`<div class="long-settings">${input('目标主珠数','targetCount',state.targetCount,1,216,1,'颗','state')}<p class="field-hint">108 只统计主珠；隔片、三通、支串另计。</p>${btn('fill-count',`调整至 ${state.targetCount} 颗主珠`,null,'secondary')}${btn('mode-example','载入此串型例串',null,'text-btn')}</div>`:''}${state.mode==='bracelet'?`<div class="field-row">${input('手围','wrist',state.wrist,10,25,.1,'cm','state')}${input('佩戴松量','ease',state.ease,0,3,.1,'cm','state')}</div><p class="field-hint">目标内周长 = 手围 + 佩戴松量</p>`:''}<label class="field"><span>线材</span><select data-field="cord" data-scope="state" aria-label="线材">${options(Object.keys(cords),state.cord)}</select></label><div class="field-row">${input('线径','cordDiameter',state.cordDiameter,.3,3,.1,'mm','state')}<label class="field"><span>线材颜色</span><div class="cord-color"><input type="color" data-field="cordColor" data-scope="state" aria-label="线材颜色" value="${state.cordColor}"><span>${state.cordColor.toUpperCase()}</span></div></label></div><label class="field"><span>收尾结</span><select data-field="knot" data-scope="state" aria-label="收尾结">${options(knots,state.knot)}</select></label>${input('结头占用长度','knotAllowance',state.knotAllowance,0,30,1,'mm','state')}<p class="field-hint">隐藏结可设为 0；外露结按实际占用调整。</p><div class="branch-actions">${btn('reverse','反转主串','rotate','text-btn')}${btn('clear','清空整串','trash','text-btn')}</div><div class="calculation-note">${icon('help',14)}<p>圈口按元素穿线长度和平均外径估算。异形珠、软线拉伸和三通走线会产生误差，实物制作前请试穿。</p></div>`;}
function selectBead(id){selected=id;activeStrand=strandOf(state,id)?.id||'main';inspector='bead';mobilePanel='bead';render();}
function openDialog(title,body,footer='',className=''){lastFocus=document.activeElement;dialog.className=className;dialog.innerHTML=`<div class="dialog-heading"><div><span class="eyebrow">YICHUAN STUDIO</span><h2>${title}</h2></div>${iconBtn('close-dialog','关闭','close')}</div><div class="dialog-body">${body}</div>${footer?`<div class="dialog-footer">${footer}</div>`:''}`;if(!dialog.open)dialog.showModal();}
function closeDialog(){dialog.close();if(lastFocus?.isConnected)lastFocus.focus();}
function planSequence(beads){return `<div class="plan-sequence">${beads.map((b,i)=>`<div><span>${String(i+1).padStart(2,'0')}</span>${beadSvg(b,36)}<p><strong>${esc(catalog.find(c=>c.id===b.material).name)}</strong><small>${b.shape} · ${b.size} × ${b.length} mm · ${b.color}</small></p></div>`).join('')}</div>`;}
function showPlan(){const m=measure(state),long=state.mode!=='bracelet';if(!state.beads.length){toast('先添加几颗喜欢的珠子，再生成清单。');return;}openDialog('穿串清单',`<div class="plan-top"><div class="plan-art">${braceletSvg(state,{numbers:true,clean:true})}</div><div><span class="plan-label">${modes[state.mode]}</span><h3>${esc(state.name)}</h3><p>${m.mainCount} 主珠 · ${m.accessoryCount} 配珠 · ${(state.branches||[]).length} 条支串</p><dl>${long?`<dt>主串穿线长度</dt><dd>${(m.span/10).toFixed(1)} cm</dd><dt>目标主珠数</dt><dd>${state.targetCount} 颗（实际 ${m.mainCount} 颗）</dd>`:`<dt>目标内周长</dt><dd>${(m.target/10).toFixed(1)} cm</dd><dt>预估内周长</dt><dd>${(m.inner/10).toFixed(1)} cm（${m.fit}）</dd>`}<dt>线材 / 线径</dt><dd>${state.cord} / ${state.cordDiameter} mm <i class="inline-color" style="background:${state.cordColor}"></i> ${state.cordColor}</dd><dt>收尾方式</dt><dd>${state.knot} · 结头占长 ${state.knotAllowance} mm</dd><dt>备线参考</dt><dd>至少 ${m.cordCm} cm（含支串）</dd></dl></div></div><p class="plan-note">按下面的编号顺序穿入；盘绕为摆放示意，不改变珠序。主串备线含 20 cm 余量，每条支串含 10 cm 余量，复杂走线需额外留线，珠孔请核对实物。</p><h3 class="section-label">01 <span>准备材料</span></h3><div class="table-scroll"><table><thead><tr><th>材料</th><th>款式</th><th>外径 × 穿线长度</th><th>颜色</th><th>数量</th></tr></thead><tbody>${materials(state).map(b=>`<tr><td>${esc(b.name)}</td><td>${b.shape}</td><td>${b.size} × ${b.length} mm</td><td><i class="inline-color" style="background:${b.color}"></i>${b.color}</td><td>${b.count}</td></tr>`).join('')}</tbody></table></div><h3 class="section-label">02 <span>主串穿入顺序</span></h3>${planSequence(state.beads)}${(state.branches||[]).map((br,i)=>`<h3 class="section-label">支串 ${i+1}<span>${esc(br.name)}</span></h3><p class="plan-note">挂在主串第 ${state.beads.findIndex(b=>b.id===br.anchor)+1} 个元素上。支串图中编号为 ${i+1}·1、${i+1}·2…，从挂点向末端依次穿入。</p>${planSequence(br.beads)}`).join('')}<h3 class="section-label">03 <span>试穿与收尾</span></h3><ol class="making-steps"><li>按主串编号摆好并穿入线材，暂不打死结。</li><li>按挂点编号安装支串；三通的第三孔按实物孔道连接收尾配饰。</li><li>核对主珠数量、松紧及配饰朝向，再用${state.knot}收尾。</li><li>确认结头稳定后，剪除多余线头。</li></ol>`,`${btn('export-json','备份方案','download','secondary')}${btn('export-png','保存搭配图','image','secondary')}${btn('print','打印 / 保存 PDF','print','primary')}`,'plan-dialog');}
function showSaved(){openDialog('我的方案',`<p class="dialog-intro">方案保存在当前浏览器中。换设备前，可导出 JSON 备份后再导入。</p><div class="saved-grid">${saved.length?saved.map((item,i)=>`<div class="saved-card"><div class="mini-ring">${braceletSvg(item.data,{clean:true})}</div><h3>${esc(item.data.name)}</h3><p>${measure(item.data).mainCount} 主珠 · ${new Date(item.at).toLocaleDateString('zh-CN')}</p><div>${btn('load-saved','继续搭配','arrow','secondary',`data-index="${i}"`)}${iconBtn('remove-saved','删除保存的方案','trash',`data-index="${i}"`)}</div></div>`).join(''):'<div class="empty-saved">还没有收藏的方案。<br>完成搭配后，点击“保存方案”留住它。</div>'}</div>`,`${btn('import','导入方案','import','secondary')}${btn('export-json','导出当前方案','download','primary')}`,'saved-dialog');}
function exportJSON(){download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),safeName()+'.json');toast('方案备份已导出，可在另一设备导入。');}
const safeName=()=>state.name.replace(/[<>:"/\\|?*]/g,'_')||'我的手串';
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function exportPNG(){const svg=braceletSvg(state,{numbers:true,clean:true}).replace('<svg ','<svg width="1488" height="1200" ');const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));const img=new Image;img.onload=()=>{try{const canvas=document.createElement('canvas');canvas.width=1600;canvas.height=1550;const ctx=canvas.getContext('2d');ctx.fillStyle='#f7f4ec';ctx.fillRect(0,0,1600,1550);ctx.fillStyle='#2b4a3b';ctx.font='42px sans-serif';ctx.textAlign='center';ctx.fillText(state.name,800,104,1450);ctx.fillStyle='#858775';ctx.font='20px sans-serif';ctx.fillText('一串  YICHUAN STUDIO · 我的穿串方案',800,151);ctx.drawImage(img,56,170,1488,1200);const m=measure(state);ctx.fillStyle='#425247';ctx.font='25px sans-serif';ctx.fillText(`${m.mainCount} 主珠 · ${state.mode==='bracelet'?'内周长约 '+(m.inner/10).toFixed(1):'主串长度 '+(m.span/10).toFixed(1)} cm · ${state.cord} ${state.cordDiameter} mm · ${state.knot}`,800,1430);ctx.fillStyle='#8b8b7a';ctx.font='20px sans-serif';ctx.fillText('按编号穿入，支串按挂点安装 · 尺寸与配饰朝向请核对实物',800,1481);canvas.toBlob(blob=>{if(blob){download(blob,safeName()+'.png');toast('搭配图已导出。');}else toast('图片导出失败，请重试。');},'image/png');}catch{toast('图片导出失败，请重试。');}finally{URL.revokeObjectURL(url);}};img.onerror=()=>{URL.revokeObjectURL(url);toast('图片生成失败，请重试。');};img.src=url;}
function add(id){const strand=currentStrand();if(id.startsWith('photo-')&&!allBeads(state).some(b=>b.material===id)&&new Set(allBeads(state).filter(b=>b.material.startsWith('photo-')).map(b=>b.material)).size>=12){toast('每份方案最多使用 12 种照片素材。');return;}if(strand.beads.length>=(strand.id==='main'?300:40)||allBeads(state).length>=600){toast('主串最多 300 个元素，支串最多 40 个，整份方案最多 600 个。');return;}const c=catalog.find(c=>c.id===id);change(()=>{const b=makeBead(id),i=strand.beads.findIndex(b=>b.id===selected);strand.beads.splice(insertMode==='after'&&i>=0?i+1:strand.beads.length,0,b);selected=b.id;inspector='bead';},`已穿入${c.name}`);}
document.addEventListener('click',async e=>{
 const mobile=e.target.closest('[data-mobile]');if(mobile){mobilePanel=mobile.dataset.mobile;if(mobilePanel!=='materials')inspector=mobilePanel;render();return;}
 const addEl=e.target.closest('[data-add]');if(addEl){add(addEl.dataset.add);return;}
 const sel=e.target.closest('[data-select]');if(sel){selectBead(sel.dataset.select);return;}
 const cat=e.target.closest('[data-category]');if(cat){category=cat.dataset.category;query='';render();return;}
 const ins=e.target.closest('[data-inspector]');if(ins){inspector=ins.dataset.inspector;mobilePanel=inspector;render();return;}
 const surface=e.target.closest('[data-bg]');if(surface){bg=surface.dataset.bg;render();return;}
 const color=e.target.closest('[data-color]');if(color&&selectedBead()){change(()=>selectedBead().color=color.dataset.color);return;}
 const action=e.target.closest('[data-action]');if(!action||action.disabled)return;const a=action.dataset.action,b=selectedBead(),strand=currentStrand(),idx=strand.beads.indexOf(b);
 switch(a){
 case 'studio':window.scrollTo({top:0,behavior:'smooth'});break;
 case 'plan':showPlan();break;
 case 'save':try{if(saved.length>=50){toast('已保存 50 份方案，请先删除不需要的方案或导出备份。');break;}saved.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),data:clone(state)});await writeStorage(SAVED,saved);toast('已存入「我的方案」，可以随时继续搭配。');}catch{saved.shift();toast('本机保存空间不足，请导出 JSON 备份。');}break;
 case 'saved':showSaved();break;
 case 'load-saved':change(()=>{state=validate(saved[Number(action.dataset.index)].data);selected=state.beads[0]?.id;},'方案已载入，可撤销返回刚才的搭配。');closeDialog();break;
 case 'remove-saved':{const old=[...saved];try{saved.splice(Number(action.dataset.index),1);await writeStorage(SAVED,saved);showSaved();toast('已删除保存的方案，当前工作台不受影响。');}catch{saved=old;toast('未能删除，请重试。');}break;}
 case 'close-dialog':closeDialog();break;
 case 'undo':if(history.length){future.push(clone(state));state=history.pop();selected=allBeads(state).some(b=>b.id===selected)?selected:state.beads[0]?.id;persist();render();}break;
 case 'redo':if(future.length){history.push(clone(state));state=future.pop();selected=allBeads(state).some(b=>b.id===selected)?selected:state.beads[0]?.id;persist();render();}break;
 case 'clear':change(()=>{state.beads=[];state.branches=[];activeStrand='main';selected=null;},'已清空排列，可以撤销恢复。');break;
 case 'reverse':change(()=>state.beads.reverse(),'穿串顺序已反转。');break;
 case 'duplicate':if(b){if(strand.beads.length>=(strand.id==='main'?300:40)||allBeads(state).length>=600){toast('元素数量已到上限。');break;}change(()=>{const copy={...b,id:crypto.randomUUID()};strand.beads.splice(idx+1,0,copy);selected=copy.id;},'已复制选中元素。');}break;
 case 'delete':if(b)change(()=>{removeBead(state,b.id);selected=strand.beads[Math.max(0,idx-1)]?.id;});break;
 case 'move-left':if(idx>0)change(()=>moveItem(strand,idx,idx-1));break;
 case 'move-right':if(idx>=0&&idx<strand.beads.length-1)change(()=>moveItem(strand,idx,idx+1));break;
 case 'apply-all':if(b)change(()=>{for(const x of allBeads(state))if(x.material===b.material)Object.assign(x,{...b,id:x.id,countAsMain:x.countAsMain});},'同种材料的颜色、款式和尺寸已统一。');break;
 case 'numbers':numbers=!numbers;render();break;
 case 'view-3d':viewMode='3d';zoom=viewer?.zoom||1;render();break;
 case 'view-2d':viewMode='2d';zoom=flatView.zoom;render();break;
 case 'auto-rotate':if(viewer){viewer.auto=!viewer.auto;render();}break;
 case 'reset-view':if(viewMode==='3d')viewer?.reset();else setFlatView({zoom:1,x:0,y:0});render();break;
 case 'zoom-in':if(viewMode==='3d'&&viewer)viewer.setZoom(zoom+.1);else setFlatView({...flatView,zoom:zoom+.25});break;
 case 'zoom-out':if(viewMode==='3d'&&viewer)viewer.setZoom(zoom-.1);else setFlatView({...flatView,zoom:zoom-.25});break;
 case 'upload-photo':photoEditor.open();break;
 case 'export-view':if(viewMode==='2d'||viewError){exportPNG();break;}if(viewer){const blob=await viewer.exportImage();if(blob){download(blob,safeName()+'-立体视角.png');toast('已保存当前立体视角（透明背景）。');}else toast('图片导出失败，请重试。');}break;
 case 'remove-photo':{const id=action.dataset.material;if(allBeads(state).some(b=>b.material===id)){toast('该素材正在当前手串中使用，请先移除对应珠子。');break;}const next=myMaterials.filter(c=>c.id!==id);try{await writeStorage('photos',next);myMaterials=next;render();toast('已移出材料盒，保存过的方案仍保留照片。');}catch{toast('未能移除，请重试。');}break;}
 case 'browse-add':mobilePanel='materials';render();$('.materials').scrollIntoView({behavior:'smooth',block:'start'});$('#material-search').focus({preventScroll:true});break;
 case 'export-json':exportJSON();break;
 case 'export-png':exportPNG();break;
 case 'print':window.print();break;
 case 'import':$('#import-file').click();break;
 case 'templates':openDialog('从一份灵感开始',`<p class="dialog-intro">选一款作起点，每颗珠子都能继续调整。载入后可撤销回到当前搭配。</p><div class="saved-grid">${[['natural','星月 · 拾光','米白菩提 × 古法金'],['forest','山野 · 青绿','深色木珠 × 绿松石'],['gold','流金 · 日常','圆珠 × 八楞金珠'],['tibetan','藏式 · 随喜','108 主珠 · 计数器与流苏'],['mala108','108 · 静心','108 主珠 · 三通与背云'],['handheld','手持 · 随行','21 主珠 · 短支串']].map(([key,title,desc])=>`<button class="template-card" data-action="template" data-template="${key}"><div class="mini-ring">${braceletSvg(modes[key]?modeStarter(key):starter(key),{clean:true})}</div><h3>${title}</h3><p>${desc}</p><span>从这一串开始 ${icon('arrow',15)}</span></button>`).join('')}</div>`,'','saved-dialog');break;
 case 'template':change(()=>{state=modes[action.dataset.template]?modeStarter(action.dataset.template):starter(action.dataset.template);selected=state.beads[0]?.id;activeStrand='main';flatView={zoom:1,x:0,y:0};viewer?.reset();});closeDialog();toast('灵感方案已载入，开始你的搭配。');break;
 case 'layout-expanded':case 'layout-coiled':change(()=>{state.layout=a==='layout-coiled'?'coiled':'expanded';flatView={zoom:1,x:0,y:0};viewer?.reset();});break;
 case 'mode-example':openDialog('载入例串',`<p class="dialog-intro">将当前搭配换为${modes[state.mode]}例串，之后可撤销恢复。</p>`,`${btn('close-dialog','保留当前',null,'secondary')}${btn('template','载入例串',null,'primary',`data-template="${state.mode}"`)}`);break;
 case 'fill-count':{const target=state.targetCount,current=state.beads.filter(isMainBead);if(!target){toast('先设置目标主珠数。');break;}if(target===current.length){toast('主珠数量已达到目标。');break;}if(state.beads.length+target-current.length>300||allBeads(state).length+target-current.length>600){toast('补珠后会超出数量上限。');break;}change(()=>{if(target>current.length){const source=b&&strand.id==='main'&&isMainBead(b)?b:current[0]||makeBead('xingyue');const additions=Array.from({length:target-current.length},()=>({...source,id:crypto.randomUUID(),countAsMain:true}));const tee=state.beads.findIndex(x=>x.shape==='三通');state.beads.splice(tee<0?state.beads.length:tee,0,...additions);}else for(const extra of current.slice(target))removeBead(state,extra.id);},`主珠已调整为 ${target} 颗，可撤销。`);break;}
 case 'add-counter':case 'add-backcloud':case 'add-tassel':if(!b||strand.id!=='main')break;if((state.branches||[]).length>=12||allBeads(state).length+11>600){toast('支串数量已到上限。');break;}change(()=>{const br=makeBranch(b.id,a.slice(4),(state.branches||[]).length+1);state.branches.push(br);selected=br.beads[0].id;activeStrand=br.id;mobilePanel='bead';},'已悬挂支串，可单独拖排并调整挂点。');break;
 case 'flip-branch':if(strand.id!=='main')change(()=>strand.side*=-1);break;
 case 'delete-branch':if(strand.id!=='main')change(()=>{state.branches=state.branches.filter(x=>x.id!==strand.id);selected=strand.anchor;activeStrand='main';},'支串已移除，可撤销。');break;
 case 'future':openDialog(`${esc(action.dataset.feature)} · 筹备中`,`<div class="future-message">${icon('leaf',32)}<h3>先把喜欢的一串，搭出来。</h3><p>${{玩家社区:'未来在这里分享搭配、交流穿串心得。',闲置交易:'未来在这里整理与交流闲置珠子。',官方售卖:'未来可以按用料清单挑选实物材料。'}[action.dataset.feature]}</p><p>这一版专注于你的私人穿串工作台。</p></div>`,btn('close-dialog','继续穿串','arrow','primary'));break;
 case 'help':openDialog('一点提示，更快上手',`<div class="help-grid"><div><b>01</b><h3>挑选喜欢的材料</h3><p>在材料盒里点击珠子、黄金元素或配饰。默认加在选中元素之后，也可切换为排列末尾。</p></div><div><b>02</b><h3>一边排，一边看</h3><p>直接拖动串上的珠子，绿色辅助线指示插入位置；拖远后出现红色“松手删除”，松手才会删除。360° 视图拖空白旋转，双指缩放和平移。</p></div><div><b>03</b><h3>让细节刚刚好</h3><p>切换手串、藏式长串、108 或手持；展开与盘绕共用珠序。选中主串珠子可悬挂计数器、背云或流苏，支串可独立编辑。108 只统计主珠。</p></div><div><b>04</b><h3>照着方案亲手穿</h3><p>生成穿串清单，查看编号、用料和操作提示。可导出搭配图、JSON 备份，或打印保存 PDF。用“添加自己的照片”抠图后可穿入手串，JSON 备份会包含照片。</p></div></div><p class="plan-note">草稿与收藏保存在当前浏览器。Ctrl / ⌘ Z 撤销，Ctrl / ⌘ Shift Z 重做。清除浏览器数据会移除本机方案，请及时导出备份。</p>`,btn('close-dialog','开始搭配','arrow','primary'));break;
 }
});
document.addEventListener('input',e=>{const t=e.target;if(t.id==='material-search'){query=t.value.trim();$('#material-grid').innerHTML=renderCatalog();return;}if(t.type==='number'&&t.dataset.field&&t.value!==''&&Number.isFinite(Number(t.value))&&Number(t.value)>=Number(t.min)&&Number(t.value)<=Number(t.max)){const key=t.dataset.field,scope=t.dataset.scope;t.dispatchEvent(new Event('change',{bubbles:true}));document.querySelector(`[data-field="${key}"][data-scope="${scope}"]`)?.focus({preventScroll:true});}});
document.addEventListener('change',e=>{
 const t=e.target;if(t.id==='design-name'){const v=t.value.trim()||'我的手串';if(v!==state.name){history.push(clone(state));future=[];state.name=v;persist();}return;}
 if(t.id==='strand-select'){activeStrand=t.value;selected=currentStrandById(t.value)?.beads[0]?.id||null;inspector='bead';mobilePanel='bead';render();return;}
 if(t.id==='branch-anchor'){const br=currentStrand();if(br.id!=='main')change(()=>br.anchor=t.value);return;}
 if(t.id==='insert-mode'){insertMode=t.value==='排列末尾'?'end':'after';return;}
 if(!t.dataset.field)return;const {field,scope}=t.dataset;let value=t.type==='checkbox'?t.checked:t.type==='number'||['coilTurns','targetCount'].includes(field)?Number(t.value):t.value;
 if(t.type==='number'&&(!t.value||!Number.isFinite(value)||value<Number(t.min)||value>Number(t.max))){toast(`请输入 ${t.min}–${t.max} 范围内的数值。`);render();return;}
 if(field==='targetCount'&&!Number.isInteger(value)){toast('主珠数量请输入整数。');render();return;}
 if(scope==='bead'&&!selectedBead())return;
 if(scope==='bead'&&field==='material'&&value.startsWith('photo-')&&!allBeads(state).some(b=>b.material===value)&&new Set(allBeads(state).filter(b=>b.material.startsWith('photo-')).map(b=>b.material)).size>=12){toast('每份方案最多使用 12 种照片素材。');render();return;}
 if((scope==='state'?state[field]:selectedBead()[field])===value)return;
 change(()=>{if(scope==='state'){if(field==='mode'){setMode(state,value);flatView={zoom:1,x:0,y:0};viewer?.reset();inspector='bracelet';mobilePanel='bracelet';}else state[field]=value;if(field==='cord'){state.cordColor=cords[value].color;state.cordDiameter=cords[value].diameter;}}else{const b=selectedBead();if(field==='material'){const c=makeBead(value);Object.assign(b,{...c,id:b.id});delete b.countAsMain;}else{const old=b.size;b[field]=value;if(field==='form')b.shape=value==='round'?'圆珠':value==='barrel'?'老型桶珠':'照片轮廓';if(field==='size'&&b.length===old&&!['隔片','流苏','吊饰'].includes(b.shape))b.length=value;}}});
});
$('#import-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>16000000)throw Error('文件过大（最多 16 MB），请选择一串导出的 JSON 方案。');const parsed=validate(JSON.parse(await file.text()));change(()=>{state=parsed;selected=state.beads[0]?.id;},'方案已导入，可继续调整。');closeDialog();}catch(err){toast(err.message.startsWith('Unexpected')?'文件格式有误，请导入有效的 JSON 方案。':err.message);}finally{e.target.value='';}});
document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select'))return;if(dialog.open)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();document.querySelector(`[data-action="${e.shiftKey?'redo':'undo'}"]`)?.click();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();document.querySelector('[data-action="save"]').click();}if(e.target.matches('.ring-bead')&&(e.key==='Enter'||e.key===' ')){e.preventDefault();selectBead(e.target.dataset.select);}});
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
function mountViewer(){
 const host=$('#preview');
 try{if(!viewer&&!viewError)viewer=new BraceletViewer(selectBead,value=>{if(viewMode==='3d'){zoom=value;const label=$('#zoom-value');if(label)label.textContent=Math.round(value*100)+'%';const plus=$('[data-action="zoom-in"]'),minus=$('[data-action="zoom-out"]');if(plus)plus.disabled=value>=8;if(minus)minus.disabled=value<=.55;}},editor);
 if(!viewer)throw Error('WebGL unavailable');viewer.mount(host);viewer.update(state,{selected,numbers});
 }catch{viewError=true;viewMode='2d';render();toast('此浏览器未启用 WebGL，已切回可拖排的平面编辑。');}
}

function currentStrandById(id){return id==='main'?{id:'main',beads:state.beads}:state.branches.find(br=>br.id===id);}
render();
