import {beadSvg} from './visuals.js';
import {allBeads,strandOf} from './model.js';
import {stringLayout,dropTarget} from './layout.js';
export function createDirectEditor({getState,getViewer,getMode,select,commit,onFlatView,getFlatView}){
 let drag=null,layer=null,suppressUntil=0,flat=null;
 const removeLayer=()=>{layer?.remove();layer=null;document.body.classList.remove('bead-drag-active');};
 function projectedFlat(){const svg=document.querySelector('#preview #bracelet-svg');if(!svg?.getScreenCTM)return [];const matrix=svg.getScreenCTM();if(!matrix)return [];const project=p=>{const v=svg.createSVGPoint();v.x=p.x;v.y=-p.y;const screen=v.matrixTransform(matrix);return {x:screen.x,y:screen.y};};return stringLayout(getState()).strands.map(st=>({...st,nodes:st.nodes.map(n=>({...project(n),id:n.bead.id,index:n.index})),start:st.start&&project(st.start),end:st.end&&project(st.end)}));}
 function start(id,point){const s=getState(),bead=allBeads(s).find(b=>b.id===id),strand=strandOf(s,id);if(!bead||!strand)return;drag={id,bead,strand:strand.id,point,target:null};getViewer()?.setDragged(id);document.querySelector(`#preview [data-select="${id}"]`)?.classList.add('drag-source');layer=document.createElement('div');layer.className='bead-drag-layer';layer.innerHTML=`<svg class="insertion-guide" aria-hidden="true"><path class="guide-neighbors"/><path class="guide-connector"/><line class="guide-slot"/><circle class="guide-point" r="4"/></svg><div class="bead-drag-ghost">${beadSvg(bead,52)}</div><div class="drop-message" role="status" aria-live="polite"></div>`;document.body.appendChild(layer);document.body.classList.add('bead-drag-active');move(point);}
 function move(point){if(!drag)return;const strands=getMode()==='3d'&&getViewer()?getViewer().projectedStrands():projectedFlat(),st=strands.find(s=>s.id===drag.strand);if(!st)return;drag.target=dropTarget(st,point,drag.id);drag.point=point;const t=drag.target;layer.classList.toggle('is-delete',t.remove);const ghost=layer.querySelector('.bead-drag-ghost');ghost.style.left=point.x+'px';ghost.style.top=point.y+'px';const msg=layer.querySelector('.drop-message');msg.textContent=t.remove?'松手删除 · 可撤销':`${st.name} · ${t.label}`;msg.style.left=Math.max(100,Math.min(innerWidth-100,point.x))+'px';msg.style.top=Math.max(12,Math.min(innerHeight-48,point.y-84))+'px';const svg=layer.querySelector('svg.insertion-guide');svg.style.visibility=t.remove?'hidden':'visible';const a=t.a,b=t.b,dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1,nx=-dy/len*19,ny=dx/len*19;layer.querySelector('.guide-neighbors').setAttribute('d',`M${a.x} ${a.y}L${b.x} ${b.y}`);layer.querySelector('.guide-connector').setAttribute('d',`M${point.x} ${point.y}L${t.x} ${t.y}`);const line=layer.querySelector('.guide-slot');for(const [k,v] of Object.entries({x1:t.x-nx,y1:t.y-ny,x2:t.x+nx,y2:t.y+ny}))line.setAttribute(k,v);const dot=layer.querySelector('.guide-point');dot.setAttribute('cx',t.x);dot.setAttribute('cy',t.y);}
 function end({cancel=false}={}){if(!drag)return;const d=drag;drag=null;removeLayer();getViewer()?.setDragged(null);document.querySelectorAll('.drag-source').forEach(el=>el.classList.remove('drag-source'));suppressUntil=Date.now()+400;if(!cancel&&d.target)commit(d.id,d.target);}
 const points=new Map;
 document.addEventListener('pointerdown',e=>{const host=e.target.closest('#preview');if(!host||host.querySelector('.three-canvas')||e.button>0)return;const el=e.target.closest('[data-select]');points.set(e.pointerId,{x:e.clientX,y:e.clientY});host.setPointerCapture?.(e.pointerId);if(points.size===1)flat={id:el?.dataset.select,start:{x:e.clientX,y:e.clientY},old:{x:e.clientX,y:e.clientY},moved:false,pinch:false};else if(flat){flat.pinch=true;flat.moved=true;suppressUntil=Date.now()+400;end({cancel:true});}});
 document.addEventListener('pointermove',e=>{if(!flat||!points.has(e.pointerId))return;const next={x:e.clientX,y:e.clientY},old=points.get(e.pointerId);if(points.size>=2){const a=[...points.values()],before=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);points.set(e.pointerId,next);const b=[...points.values()],after=Math.hypot(b[0].x-b[1].x,b[0].y-b[1].y);const v=getFlatView();onFlatView({zoom:before>0?v.zoom*after/before:v.zoom,x:v.x+(next.x-old.x)/2,y:v.y+(next.y-old.y)/2});}else if(!flat.pinch){if(Math.hypot(next.x-flat.start.x,next.y-flat.start.y)>7)flat.moved=true;if(flat.moved){e.preventDefault();if(flat.id){if(!drag)start(flat.id,flat.start);move(next);}else{const v=getFlatView();onFlatView({...v,x:v.x+next.x-old.x,y:v.y+next.y-old.y});}}points.set(e.pointerId,next);}},{passive:false});
 document.addEventListener('pointerup',e=>{if(!points.has(e.pointerId))return;points.delete(e.pointerId);if(drag){move({x:e.clientX,y:e.clientY});end();}else if(flat?.id&&!flat.moved&&!flat.pinch){suppressUntil=Date.now()+400;select(flat.id);}if(!points.size)flat=null;});
 const cancelFlat=e=>{if(points.has(e.pointerId)){points.delete(e.pointerId);end({cancel:true});if(flat)flat.pinch=true;if(!points.size)flat=null;}};
 document.addEventListener('pointercancel',cancelFlat);document.addEventListener('lostpointercapture',cancelFlat);
 document.addEventListener('wheel',e=>{const host=e.target.closest('#preview');if(!host||host.querySelector('.three-canvas')||drag)return;e.preventDefault();const v=getFlatView();onFlatView({...v,zoom:v.zoom*Math.exp(-e.deltaY*.001)});},{passive:false});
 document.addEventListener('click',e=>{if(Date.now()<suppressUntil&&e.target.closest('#preview,[data-select]')){e.preventDefault();e.stopImmediatePropagation();}},true);
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){end({cancel:true});points.clear();flat=null;}});
 window.addEventListener('blur',()=>{end({cancel:true});points.clear();flat=null;});
 return {start,move,end,projectedFlat};
}
